### PR TITLE
Set UFW rule to allow NTP synchronization

### PR DESCRIPTION
**Pull request by lasarojc**
ditto

### CODE REVIEW

**Comment by hvanz** [comment]
Now we use cloud-init for setting up the DO machines, including installing packages and the firewall. So you just need to add the line:
```
- ufw allow out proto udp to any port 123
```
to `tf/user-data.txt`. This will affect all the resources (nodes, prometheus and loadrunner).

**Comment by cason** [comment]
@hvanz, given what you said, why we still have all these files on the repo?

**Comment by hvanz** [comment]
Not all was ported to cloud-init (yet?) and I'm not sure exactly what cloud-init can handle. For the moment, most of the firewall settings are in `tf/user-data.txt`.

**Review by hvanz — APPROVED** [review]
Just tested manually with `timedatectl timesync-status` and it's working.

**Comment by lasarojc** [comment]
> Now we use cloud-init for setting up the DO machines, including installing packages and the firewall. So you just need to add the line:
> 
> ```
> - ufw allow out proto udp to any port 123
> ```
> 
> to `tf/user-data.txt`. This will affect all the resources (nodes, prometheus and loadrunner).

Thanks, @hvanz . Changed as you suggested and as we confirmed to be working.

**Pull request merged**
